language: php
os: linux
dist: xenial

php:
  - 7.2
  - 7.3
  - 7.4

before_install:
  - phpenv config-rm xdebug.ini

before_script:
  - composer install

script:
  - composer test

branches:
  only:
    - main
    - /develop/

after_success:
  - bash <(curl -s https://codecov.io/bash)

